language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

stages:
  - linting
  - test

jobs:
  include:
    - stage: linting
      env:
        - LINT_CHECK="1"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="odoo/odoo" TRANSIFEX="1"
env:
  global:
  - VERSION="15.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='jjscarafia'
  # to get secure, run 'travis encrypt TRANSIFEX_PASSWORD=[transifex_password] -r [github_repo]'
  # example of github repo 'ingadhoc/odoo-infrastructure'
  - secure: GXC5OYklbsRFtB2Ii5XexWoesO7Rgdd8ueFpsik8k+T4HAcZZqPUphJTWgBbGraNi961NJdzCJ4nYS2WGu3a1QcUfd0wOs83vIeioke0G0WtQahzx3eftUTlzJYfYztt1FiaEmfGUUNgqaJ5NxdWIPJEob7NTs+UnZHSKk1C36RNRsbcnVgPxNzjX1kQ3izZdj7wsy5eGtGNgazfTh9gscyWrBSXOkLFW52DQXRLHuaNz4GpV7/tkOF5sUuYO58xcPqNKYfdv9keFXtnsfBDwWpaiaNvViAYQ1BuI/+PXKMybpV5bGhSlVbxCkia74yuXOIK7w/khMJuJJbvj7Tlt8hXC2e1Dp7z3uWJoZzdBOm+CRa5E6deCeW80swyu63D8HyEezP3SL9TLi3VIdJdNNJkLTQxV9RLBXqXrwf2OXHB4e6uPc5WN5xLia92yzG1Je7mHYqShqgYWOTPcDGc9r8L9gCRyZnwG9wbXunIkhnSWheIHPK6Q9Otvl32jVPCfx9XbcRUyCIomjDLA85blub9INFF8LNd39oo3Owp2UGU97odSZywq+o5OaxuSBnQulaFVfm7cIKV6n8kSfqh40KwZId6MaynqwQCjWFQbHXkw7AVN1eedttmk2OmTrNGclR8im41X+tK1+IxH3FoqqxyxS3IhoceafOXLbmaKeA=
  - TRANSIFEX_ORGANIZATION='adhoc'
  - TRANSIFEX_TEAM='46451'

install:
  - if [[ "${OCA_RUNBOT}" == "1" ]]; then locale-gen es_AR.UTF-8 && locale-gen es_ES.UTF-8; fi
  - git clone --depth=1 https://github.com/ingadhoc/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  # - printf '[options]\n\nserver_wide_modules = base,web,l10n_ar_demo\n' > ${HOME}/.openerp_serverrc

script:
  - travis_run_tests

after_success:
  # enable aeroo docs conversion
  # - if [[ "${OCA_RUNBOT}" == "1" ]]; then psql openerp_test -c "INSERT INTO ir_config_parameter (key, value) VALUES ('aeroo.docs_host', 'runbot.adhoc.com.ar'), ('aeroo.docs_port', '8989'), ('aeroo.docs_enabled', 'True')"; fi
  - travis_after_tests_success
