language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

stages:
  - linting
  - test

jobs:
  include:
    - stage: linting
      env:
        - LINT_CHECK="1"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="odoo/odoo" TRANSIFEX="1"
env:
  global:
  - VERSION="13.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='jjscarafia'
  # to get secure, run 'travis encrypt TRANSIFEX_PASSWORD=[transifex_password] -r [github_repo]'
  # example of github repo 'ingadhoc/odoo-infrastructure'
  - secure: UXo8IHxP20/7qseBeAovmDnx9B9q/TrhgAc9DFhMwhKcaGBgmSQTmq+YMnZUpW+H1V9V+DRApmg8KvAjIo7lNci41yIL8fwhdo4T6YYbkvrbwbh8ANkzfF8kk2TJN41n8Cl0DokgxR+X6+ef0XjtfJL0A1QyeX+KW+9PzsdN1XvQtEmJACsL8ILDxL0x9MFATGzx+IoZGAHhdnwuMuugImOBQ/+svSMbVYDQ2h7dQqJpwlA1Uu4KcliIO5H2NHYExag9PMzvlUYB4gJLebkJk6gAHDLlanb+0wd0Cb9swJ9yVeS3/L4lWJW+5tTIYjuG4emRZZFwCkJUADeeuXsEeuzXCSPKou7dPisDH0DzspqUmvCVco1bECR62KSdKwgxHDzILNOOJXotbEGaN06gFfla+VXuSQszig/rOyyVPZwIRA2mbBdmeUVP/hS0OS7lIM730gvYfOWT9Gq64RQDW1FeAVPt7UshuDJtWyUaP9U+DPBvomMgU4ID72603db5YLoNrsEFapG98eUgF5oMa0FpNmmadOYBeHg4y7Kprm9vo0920UdNdQu3bNAWWXCyOsPUzXaxSUZ+jBo99thURF+6zYM37qDJSjPBvdFxPEWj6YdsrJ+LN/4gcjzYUMvPfPTgMHiEMq2ECFy8ZgNA93GAYYv5+v5NiUy6J2HYYLw=
  - TRANSIFEX_ORGANIZATION='adhoc-ee'
  - TRANSIFEX_TEAM='116364'

install:
  - if [[ "${OCA_RUNBOT}" == "1" ]]; then locale-gen es_AR.UTF-8 && locale-gen es_ES.UTF-8; fi
  - git clone --depth=1 https://github.com/ingadhoc/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  # - printf '[options]\n\nserver_wide_modules = base,web,l10n_ar_demo\n' > ${HOME}/.openerp_serverrc

script:
  - travis_run_tests

after_success:
  # enable aeroo docs conversion
  # - if [[ "${OCA_RUNBOT}" == "1" ]]; then psql openerp_test -c "INSERT INTO ir_config_parameter (key, value) VALUES ('aeroo.docs_host', 'runbot.adhoc.com.ar'), ('aeroo.docs_port', '8989'), ('aeroo.docs_enabled', 'True')"; fi
  - travis_after_tests_success
