from . import base_lenguage_install
from . import hr_applicant
from . import hr_department
from . import hr_job
from . import res_config_settings
from . import res_users
from . import sale_order
from . import purchase
from . import res_company
from . import product_template
from . import res_partner
from . import website
